from __future__ import annotations

from typing import Any

from .normalization import now_iso


def render_policy_markdown(
    state: dict[str, Any],
    proposals: list[dict[str, Any]],
) -> str:
    lines = [
        "# Project Policies",
        "",
        "> Generated from `.madspec/system/policy/state.json`. Do not edit this file as canonical state.",
        "",
        f"- Revision: `{state.get('revision', 1)}`",
        f"- Updated: `{state.get('updatedAt') or state.get('createdAt') or now_iso()}`",
        f"- Pending proposals: `{len([item for item in proposals if item.get('status') == 'pending'])}`",
        "",
        "## Active Policies",
    ]
    active = [item for item in state.get("policies", []) if item.get("status") == "active"]
    if not active:
        lines.append("- No active policies")
    for policy in active:
        rule = policy.get("rule") or {}
        lines.extend(
            [
                f"### {policy['title']} (`{policy['policyId']}`)",
                "",
                f"- Kind: `{policy['kind']}`",
                f"- Enforcement: `{policy['enforcement']}`",
                f"- Source: `{policy['source']}`",
                (
                    "- Scope: `all`"
                    if not policy.get("scope", {}).get("stages")
                    else "- Scope stages: `"
                    + ", ".join(policy.get("scope", {}).get("stages", []))
                    + "`"
                ),
            ]
        )
        if rule.get("ruleType"):
            lines.append(f"- Rule type: `{rule['ruleType']}`")
        lines.extend(["", policy.get("description") or "_No description_", ""])

    deprecated = [item for item in state.get("policies", []) if item.get("status") == "deprecated"]
    lines.extend(["## Deprecated Policies", ""])
    if not deprecated:
        lines.append("- No deprecated policies")
    for policy in deprecated:
        lines.append(
            f"- `{policy['policyId']}` — {policy['title']} (deprecated at `{policy.get('deprecatedAt') or 'unknown'}`)"
        )

    lines.extend(["", "## Pending Proposals", ""])
    pending = [item for item in proposals if item.get("status") == "pending"]
    if not pending:
        lines.append("- No pending proposals")
    for proposal in pending:
        lines.append(
            f"- `{proposal['proposalId']}` `{proposal['action']}` -> `{proposal['policyId']}`: {proposal['summary']}"
        )
    return "\n".join(lines) + "\n"


__all__ = ["render_policy_markdown"]
