from __future__ import annotations

from madspec_cli.memory.shared.storage import now_iso

from ..domain.builtin_roles import DEFAULT_PROFILE_ID, DEFAULT_SUBAGENT_IDS, role_catalog
from ..domain.frontmatter_profiles import (
    SubagentFrontmatterProfile,
    resolve_subagent_model,
    subagent_frontmatter_profile_for_environment,
)
from ..domain.normalizers import (
    _normalize_tool_policy,
    normalize_catalog_role,
    normalize_subagent_definition,
    unique_role_ids,
    validate_subagent_definition_dependencies,
    validate_subagent_id,
)
from ..domain.tool_translation import TOOL_POLICY_KEYS, TOOL_TRANSLATORS, ToolTranslator, translate_tool_policy
from .artifact_export import export_agents_artifact
from .catalog_store import (
    AGENTS_CATALOG_SCHEMA_VERSION,
    append_agent_history,
    append_agent_proposal,
    body_file_name,
    body_file_path,
    build_agents_diff,
    build_profile_payload,
    create_profile_proposal,
    default_agents_catalog,
    enabled_subagents_for_output,
    find_effective_subagent,
    list_agent_history,
    list_agent_proposals,
    load_agents_catalog,
    load_effective_subagents,
    migrate_agents_catalog,
    project_body_relative_path,
    remove_catalog_role,
    save_agents_catalog,
    upsert_catalog_role,
)
from .render_workspace import (
    MANAGED_FILE_PREFIX,
    load_subagent_body,
    load_subagent_template_body,
    managed_role_id_from_path,
    managed_subagent_filename,
    render_fallback_guidance_file,
    render_native_subagent_file,
    render_workspace_agents,
    serialize_frontmatter,
)
from .state_store import (
    AGENTS_SCHEMA_VERSION,
    AgentsPaths,
    build_environment_profile,
    default_agents_state,
    detect_agent_environment,
    ensure_agents_layout,
    get_agents_paths,
    load_agents_state,
    migrate_agents_state,
    save_agents_state,
)


__all__ = [
    "AGENTS_CATALOG_SCHEMA_VERSION",
    "AGENTS_SCHEMA_VERSION",
    "AgentsPaths",
    "DEFAULT_PROFILE_ID",
    "DEFAULT_SUBAGENT_IDS",
    "MANAGED_FILE_PREFIX",
    "TOOL_POLICY_KEYS",
    "TOOL_TRANSLATORS",
    "SubagentFrontmatterProfile",
    "ToolTranslator",
    "_normalize_tool_policy",
    "append_agent_history",
    "append_agent_proposal",
    "body_file_name",
    "body_file_path",
    "build_agents_diff",
    "build_environment_profile",
    "build_profile_payload",
    "create_profile_proposal",
    "default_agents_catalog",
    "default_agents_state",
    "detect_agent_environment",
    "enabled_subagents_for_output",
    "ensure_agents_layout",
    "export_agents_artifact",
    "find_effective_subagent",
    "get_agents_paths",
    "list_agent_history",
    "list_agent_proposals",
    "load_agents_catalog",
    "load_agents_state",
    "load_effective_subagents",
    "load_subagent_body",
    "load_subagent_template_body",
    "managed_role_id_from_path",
    "managed_subagent_filename",
    "migrate_agents_catalog",
    "migrate_agents_state",
    "normalize_catalog_role",
    "normalize_subagent_definition",
    "now_iso",
    "project_body_relative_path",
    "remove_catalog_role",
    "render_fallback_guidance_file",
    "render_native_subagent_file",
    "render_workspace_agents",
    "resolve_subagent_model",
    "role_catalog",
    "save_agents_catalog",
    "save_agents_state",
    "serialize_frontmatter",
    "subagent_frontmatter_profile_for_environment",
    "translate_tool_policy",
    "unique_role_ids",
    "upsert_catalog_role",
    "validate_subagent_definition_dependencies",
    "validate_subagent_id",
]
