from __future__ import annotations

from typing import Any

from ..shared.text_lists import normalize_plain_text_list_with_repairs
from .capture_models import CaptureInputs
from .shared import normalize_text_list


def build_capture_inputs(
    *,
    stage: str,
    status: str,
    summary: str | None = None,
    facts: list[str] | None = None,
    decisions: list[str] | None = None,
    contracts: list[str] | None = None,
    evidence: list[str] | None = None,
    questions: list[str] | None = None,
    pending_actions: list[str] | None = None,
    project_name: str | None = None,
    system_overview: str | None = None,
    audiences: list[str] | None = None,
    scenarios: list[str] | None = None,
    pain_points: list[str] | None = None,
    feature_p1: list[str] | None = None,
    feature_p2: list[str] | None = None,
    feature_p3: list[str] | None = None,
    constraints: list[str] | None = None,
    assumptions: list[str] | None = None,
    next_actions: list[str] | None = None,
    design_overview: str | None = None,
    platforms: list[str] | None = None,
    zones: list[str] | None = None,
    screens: list[str] | None = None,
    screen_features: list[str] | None = None,
    flows: list[str] | None = None,
    flow_steps: list[str] | None = None,
    flow_alternatives: list[str] | None = None,
    navigation: list[str] | None = None,
    platform_constraints: list[str] | None = None,
    screen_data: list[str] | None = None,
    stack_overview: str | None = None,
    project_type: str | None = None,
    framework: str | None = None,
    requirements: list[str] | None = None,
    structure_notes: list[str] | None = None,
    preferences: list[str] | None = None,
    tech_constraints: list[str] | None = None,
    stack_components: list[str] | None = None,
    libraries: list[str] | None = None,
    code_organization: str | None = None,
    alternatives: list[str] | None = None,
    architecture_overview: str | None = None,
    project_structure: str | None = None,
    directories: list[str] | None = None,
    entities: list[str] | None = None,
    entity_fields: list[str] | None = None,
    entity_relationships: list[str] | None = None,
    entity_states: list[str] | None = None,
    endpoints: list[str] | None = None,
    endpoint_screens: list[str] | None = None,
    endpoint_fields: list[str] | None = None,
    endpoint_errors: list[str] | None = None,
    integrations: list[str] | None = None,
    code_principles: list[str] | None = None,
    architecture_patterns: list[str] | None = None,
    security_notes: list[str] | None = None,
    performance_notes: list[str] | None = None,
    plan_overview: str | None = None,
    planning_principles: list[str] | None = None,
    deploy_overview: str | None = None,
    deploy_goals: list[str] | None = None,
    environments: list[str] | None = None,
    deployment_units: list[str] | None = None,
    config_notes: list[str] | None = None,
    secret_notes: list[str] | None = None,
    cicd_triggers: list[str] | None = None,
    cicd_steps: list[str] | None = None,
    release_artifacts: list[str] | None = None,
    migration_notes: list[str] | None = None,
    backup_notes: list[str] | None = None,
    recovery_checks: list[str] | None = None,
    observability_notes: list[str] | None = None,
    security_controls: list[str] | None = None,
    release_strategy: str | None = None,
    rollback_strategy: str | None = None,
    feature_goal: str | None = None,
    problem: str | None = None,
    expected_outcome: str | None = None,
    existing_modules: list[str] | None = None,
    modified_files: list[str] | None = None,
    new_files: list[str] | None = None,
    interface_contracts: list[str] | None = None,
    dependencies: list[str] | None = None,
    risks: list[str] | None = None,
    recommendations: list[str] | None = None,
    tech_notes: list[str] | None = None,
    architecture_notes: list[str] | None = None,
) -> CaptureInputs:
    warnings: list[dict[str, str]] = []

    def normalize_plain(field_name: str, values: list[str] | None) -> list[str]:
        normalized, field_warnings = normalize_plain_text_list_with_repairs(values, field_name=field_name)
        warnings.extend(field_warnings)
        return normalized

    def normalize_scalar(value: Any) -> str:
        return value.strip() if isinstance(value, str) else ""

    return CaptureInputs(
        stage=stage,
        status=status,
        summary=normalize_scalar(summary),
        warnings=warnings,
        facts=normalize_plain("facts", facts),
        decisions=normalize_plain("decisions", decisions),
        contracts=normalize_plain("contracts", contracts),
        evidence=normalize_plain("evidence", evidence),
        questions=normalize_plain("questions", questions),
        pending_actions=normalize_plain("pending_actions", pending_actions),
        project_name=normalize_scalar(project_name),
        system_overview=normalize_scalar(system_overview),
        audiences=normalize_plain("audiences", audiences),
        scenarios=normalize_plain("scenarios", scenarios),
        pain_points=normalize_plain("pain_points", pain_points),
        feature_p1=normalize_text_list(feature_p1),
        feature_p2=normalize_text_list(feature_p2),
        feature_p3=normalize_text_list(feature_p3),
        constraints=normalize_plain("constraints", constraints),
        assumptions=normalize_plain("assumptions", assumptions),
        next_actions=normalize_plain("next_actions", next_actions),
        design_overview=normalize_scalar(design_overview),
        platforms=normalize_plain("platforms", platforms),
        zones=normalize_text_list(zones),
        screens=normalize_text_list(screens),
        screen_features=normalize_text_list(screen_features),
        flows=normalize_text_list(flows),
        flow_steps=normalize_text_list(flow_steps),
        flow_alternatives=normalize_text_list(flow_alternatives),
        navigation=normalize_text_list(navigation),
        platform_constraints=normalize_plain("platform_constraints", platform_constraints),
        screen_data=normalize_text_list(screen_data),
        stack_overview=normalize_scalar(stack_overview),
        project_type=normalize_scalar(project_type),
        framework=normalize_scalar(framework),
        requirements=normalize_plain("requirements", requirements),
        structure_notes=normalize_plain("structure_notes", structure_notes),
        preferences=normalize_plain("preferences", preferences),
        tech_constraints=normalize_plain("tech_constraints", tech_constraints),
        stack_components=normalize_text_list(stack_components),
        libraries=normalize_text_list(libraries),
        code_organization=normalize_scalar(code_organization),
        alternatives=normalize_text_list(alternatives),
        architecture_overview=normalize_scalar(architecture_overview),
        project_structure=normalize_scalar(project_structure),
        directories=normalize_text_list(directories),
        entities=normalize_text_list(entities),
        entity_fields=normalize_text_list(entity_fields),
        entity_relationships=normalize_text_list(entity_relationships),
        entity_states=normalize_text_list(entity_states),
        endpoints=normalize_text_list(endpoints),
        endpoint_screens=normalize_text_list(endpoint_screens),
        endpoint_fields=normalize_text_list(endpoint_fields),
        endpoint_errors=normalize_text_list(endpoint_errors),
        integrations=normalize_text_list(integrations),
        code_principles=normalize_plain("code_principles", code_principles),
        architecture_patterns=normalize_text_list(architecture_patterns),
        security_notes=normalize_plain("security_notes", security_notes),
        performance_notes=normalize_plain("performance_notes", performance_notes),
        plan_overview=normalize_scalar(plan_overview),
        planning_principles=normalize_plain("planning_principles", planning_principles),
        deploy_overview=normalize_scalar(deploy_overview),
        deploy_goals=normalize_plain("deploy_goals", deploy_goals),
        environments=normalize_text_list(environments),
        deployment_units=normalize_text_list(deployment_units),
        config_notes=normalize_plain("config_notes", config_notes),
        secret_notes=normalize_plain("secret_notes", secret_notes),
        cicd_triggers=normalize_plain("cicd_triggers", cicd_triggers),
        cicd_steps=normalize_plain("cicd_steps", cicd_steps),
        release_artifacts=normalize_plain("release_artifacts", release_artifacts),
        migration_notes=normalize_plain("migration_notes", migration_notes),
        backup_notes=normalize_plain("backup_notes", backup_notes),
        recovery_checks=normalize_plain("recovery_checks", recovery_checks),
        observability_notes=normalize_plain("observability_notes", observability_notes),
        security_controls=normalize_plain("security_controls", security_controls),
        release_strategy=normalize_scalar(release_strategy),
        rollback_strategy=normalize_scalar(rollback_strategy),
        feature_goal=normalize_scalar(feature_goal),
        problem=normalize_scalar(problem),
        expected_outcome=normalize_scalar(expected_outcome),
        existing_modules=normalize_text_list(existing_modules),
        modified_files=normalize_text_list(modified_files),
        new_files=normalize_text_list(new_files),
        interface_contracts=normalize_plain("interface_contracts", interface_contracts),
        dependencies=normalize_text_list(dependencies),
        risks=normalize_plain("risks", risks),
        recommendations=normalize_plain("recommendations", recommendations),
        tech_notes=normalize_plain("tech_notes", tech_notes),
        architecture_notes=normalize_plain("architecture_notes", architecture_notes),
    )
